<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN-NO5VUV5PR36" name="CategoriaTest" tests="8" failures="1" timestamp="19 Sep 2017 13:56:01 GMT" time="1.667" errors="0">
  <testcase name="insertar" time="0.432" classname="pe.com.test.CategoriaTest"/>
  <testcase name="timeOut" time="1.021" classname="pe.com.test.CategoriaTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.timeOut() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.timeOut() didn't finish within the time-out 1000
]]>
    </failure>
  </testcase> <!-- timeOut -->
  <testcase name="insertarDataProvider" time="0.024" classname="pe.com.test.CategoriaTest"/>
  <testcase name="insertarDataProvider" time="0.014" classname="pe.com.test.CategoriaTest"/>
  <testcase name="insertarDataProvider" time="0.008" classname="pe.com.test.CategoriaTest"/>
  <testcase name="actualizar" time="0.02" classname="pe.com.test.CategoriaTest"/>
  <testcase name="obtener" time="0.011" classname="pe.com.test.CategoriaTest"/>
  <testcase name="eliminar" time="0.033" classname="pe.com.test.CategoriaTest"/>
</testsuite> <!-- CategoriaTest -->
